### ISSUE TITLE
Special characters in PeanutButter.INI

### ISSUE THREAD

**Issue by theBest3000** [fluffynuts/PeanutButter#105]
## Expected Behavior
Using special characters should work.

## Actual Behavior
If runnin locally it does work. However I wrote a wrapper and complied a NuGet. Using this NuGet does not work with special characters. 
I don't know if this is a problem with Peanut Butter or with NuGet.

**Comment by fluffynuts** [comment]
Please provide more information:

1. your working local use-case
2. the project you're using to create the nuget package
3. a link to the published package

Thanks

**Comment by theBest3000** [comment]
Sorry for not responding earlier. I did not set the proper Default Encoding. With that everything work fine. Sorry.

**Comment by fluffynuts** [comment]
> Sorry for not responding earlier. I did not set the proper Default Encoding. With that everything work fine. Sorry.

No worries - thanks for reporting anyway (:
