### ISSUE TITLE
GenericBuilder should not b0rk when attempting to randomise props which are Actions or Funcs

### ISSUE THREAD

**Issue by fluffynuts** [fluffynuts/PeanutButter#14]
Currently, if you have a class or interface with a property like:
```csharp
public interface IMooCow
{
	Action<string> LogAction { get; set; }
}
```

Then `GenericBuilder` will explode when attempting default randomisation of an entity constructed for this type as you can't `Activator.CreateInstance` on an Action or Func.

What should really happen here is that the randomiser should just create an action or func which matches the required call signature and does nothing (in the case of the func should return the default value for the return type).

**Comment by fluffynuts** [comment]
Currently, consumers can work around this; in the case outlined above, define a userland builder for IMooCow and override `WithRandomProps` to do nothing (for more complex types, one would have to flesh out all of `WithRandomProps`, of course:
```csharp
public class MooCowBuilder: GenericBuilder<MooCowBuilder, IMooCow>
{
	public override MooCowBuilder WithRandomProps()
  	{
		return this;
	}
}
```

**Comment by fluffynuts** [comment]
A recent update prevents the breakage seen when attempting to construct items with delegate properties, however, they are just ignored there. I'd like to see the resolution to this issue generate delegates where possible.

**Comment by Xiaoy312** [comment]
Hi, I would like to give this a try.
