### ISSUE TITLE
Nice-to-have: nuget icons

### ISSUE THREAD

**Issue by fluffynuts** [fluffynuts/PeanutButter#15]
Seeing warnings that `<iconUrl>` is deprecated in the nuspecs raises the question of new icons, which would be checked into the PB repo.

1st prize: icons with a constant theme which communicate the purpose of each library, even if they just have a common frame/background with a little text on them.

2nd prize: a unified icon for all packages.

Preferred design:
- minimal
- flat
- catchy color
- perhaps a mascot design? Not imperitive: minimal, communicative icons would work great.

**Comment by fenwick67** [comment]
I had some ideas 😊 here they are at 64x64. I have SVGs for these if you want em bigger. 

Let me know what you think. I tried to accentuate that it's a *series* of libraries and keep it flat.

![pb](https://user-images.githubusercontent.com/8461973/66532414-54081a80-eadd-11e9-9264-0db5c52a54de.png)
![pb_wide3](https://user-images.githubusercontent.com/8461973/66532415-54a0b100-eadd-11e9-8b86-c75facb274cf.png)
![pb_switch](https://user-images.githubusercontent.com/8461973/66532421-566a7480-eadd-11e9-8bae-7a35292bc78f.png)

**Comment by fluffynuts** [comment]
Hi. Thanks for having a look at this!

Honestly, I'm not in love with the purple, but I do appreciate the effort that it must have taken to get these together. I'm not much of a designer (read: not at all!), so I don't even know how to articulate it better )': I'm a typical "customer" who will "know it when I see it". I do like the idea of the series of peanuts to communicate the suite of libraries.

I don't want to waste your time, so please feel free to tell me if I am (: What do you think of something kind of "line art" (I'm not sure if that's even the correct term -- but more kinda outlines? Perhaps with a space where a short word (eg "INI", "Utils", "MySql") could go? As in, if there was a good base, someone without design skills (like me) could overlay the text, instead of wasting your time? What do you think?
A (not very great) example of this direction is https://cdn.iconscout.com/icon/premium/png-256-thumb/adobe-photoshop-1776939-1512234.png (yes, that's well boring, and I'm sure you could do something much better -- I mean the idea, with simple, line-art-style, and a place where some kind of text-based personalization for the library could go, though I don't expect you to necessarily make _all_ of the possible icons now (and I might add more libraries later, so there's that).

I'm still very-much open for suggestions. My suggestions above may not even be that good! I bet you have to deal with idiots like me every day ):

**Comment by fluffynuts** [comment]
I also don't know if more info about this project and where the name comes from may help. If not, just ignore this; otherwise, read on (:

I started this in 2013. There was code that I rewrote often, stuff which I didn't want to write any more because I wanted to solve new problems. I wanted to port solutions to existing problems from older projects into newer ones, particularly in the realm of testing, but later on, general utilities.

I also wanted to learn more about nuget, I wanted to give something back to open-source, I wanted to help the people in my office not have to deal with common problems that we'd all dealt with.

In the meantime, this suite has gone on to "infect" people I don't know (acquaintences of friends would use it, or we'd do a project for someone and hand-off, and they'd start using it). I've met some of those people and it's a joy to know that stuff I've done can help others, even if just a little.

I've also used this to stretch my abilities -- PeanutButter.DuckTyping, for instance, allowed me to learn and grow a lot, and still delivers more usefulness to me than I would have expected. The TempDb range facilitates better testing at CI servers, and has become the standard for how tests at my current company must be run when they get to CI.

This has been a lot of fun, and hopefully will continue to be a lot of fun. And I'm honestly quite surprised at how amazing it is to be on the receiving end of hacktoberfest contributions. I participated as a contributer last year, and really, opened a couple of issues this year because some people I know seemed interested in tackling them. In the mean-time, two people I _don't_ know (yourself and another) have stepped forward to contribute. It's really quite amazing. I've contributed as an outsider to other projects before, but this year is the first time I'm seeing requests to contribute from people I don't even know, for this project.

So thanks again for contributing (:

**Comment by fenwick67** [comment]
How does this strike you?
![jar_bg](https://user-images.githubusercontent.com/8461973/66610977-2679aa80-eb8b-11e9-8d52-54257d2d0642.png)
![jar](https://user-images.githubusercontent.com/8461973/66610929-05b15500-eb8b-11e9-9754-c07b0c0df035.png)
![jar_64](https://user-images.githubusercontent.com/8461973/66611412-6d1bd480-eb8c-11e9-8a62-c1597c8754f4.png)

![jar_bg_sm](https://user-images.githubusercontent.com/8461973/66611119-8f612280-eb8b-11e9-8041-8d132abc8401.png)

Or more outliney: 
![jar_bw](https://user-images.githubusercontent.com/8461973/66611836-b7ea1c00-eb8d-11e9-931a-ffc25f565278.png)

**Comment by fluffynuts** [comment]
I'm liking the color ones! Please create a PR and include a version that I can edit & scale, eg svg, so I can add labels as needed, and so I can get the sizing right. The new standard is to have self-contained icons, but there's still some debate about the size (https://github.com/NuGet/Home/issues/352, and I've also seen mention of 128x128). The main point of this issue was to get design help with the icons, not necessarily create grunt work for all possible variants (there are 33 packages in total in the PeanutButter.* realm: http://www.nuget.org/packages?q=peanutbutter)

**Comment by fluffynuts** [comment]
this issue is resolved with #18
