### ISSUE TITLE
Nice-to-have: Nuget flavored package icons

### ISSUE THREAD

**Issue by fluffynuts** [fluffynuts/PeanutButter#20]
A recent PR has provided an SVG source icon (`resources/logo.svg`) which now needs to be applied to the arduous task of copying, applying textural labels & exporting as png for each of the published projects. There's limited space considering the final size of the icon, so here are suggestions:

PeanutButter.Utils - "Utils"
PeanutButter.RandomGenerators - "Random"
PeanutButter.INI - "INI"
PeanutButter.TrayIcon - "Tray"
PeanutButter.ServiceShell - "Service"
PeanutButter.WindowsServiceManagement - "SvcMgr"
PeanutButter.SimpleHttpServer - "HTTP"
PeanutButter.TempDb - "TempDb"
PeanutButter.XmlUtils - "Xml"
PeanutButter.DatabaseHelpers - "SQL"
PeanutButter.DatabaseHelpers.Testability - "SQL-T"
PeanutButter.FluentMigrator - "Migrate"
PeanutButter.Async - "Async"
PeanutButter.Utils.Entity - "EF"
PeanutButter.TestUtils.Generic - "TestUtils"
PeanutButter.TinyEventAggregator - "Events"
PeanutButter.DuckTyping - "Quack"
PeanutButter.TestUtils.Async - "TestAsync"
PeanutButter.SimpleHTTPServer.Testability - "HttpTest"
PeanutButter.SimpleTcpServer - "TCP"
PeanutButter.JObjectExtension - "{}"
PeanutButter.TempDb.Sqlite - "Sqlite"
PeanutButter.TempDb.LocalDb - "LocalDb"
PeanutButter.TestUtils.MVC - "MVC"
PeanutButter.TempDb.SqlCe - "SqlCe"
PeanutButter.TempDb.Runner - "DbRunner"
PeanutButter.TempDb.MySql.Connector - "MySql.Connector"
PeanutButter.TempDb.MySql.Data - "MySql.Data"

A pull request does not have to satisfy _all_ icon requirements. Feel free to PR with as many icons as you like, or as few (: This would be a good beginner task, especially if you're wanting to learn about SVG, or the PR process (:

**Comment by tammylotter** [comment]
I'd like to take this on :)

**Comment by fluffynuts** [comment]
closed by #21 ; now I just need to update packages to actually _use_ the icons...
