### ISSUE TITLE
RenameSection Method Needed for INI

### ISSUE THREAD

**Issue by ixm7** [fluffynuts/PeanutButter#32]
Currently, the only way to rename a section is to create a new one and delete the old one.
That removes all comments and changes the position of the section within the ini file. 

Please consider adding a RenameSection() method.

**Comment by fluffynuts** [comment]
@ixm7 sounds like a useful addition; I'm opening this up for #hacktoberfest (:

**Comment by fluffynuts** [comment]
This is technically resolved, though I'm still giving a think to the possibility of request of maintaining section order, which INIFile has never done before due to underlying data storage being in `Dictionary<string, string>` collections
