### ISSUE TITLE
Add Option (or default) for Section Gaps

### ISSUE THREAD

**Issue by ixm7** [fluffynuts/PeanutButter#33]
Currently, after persisting, there are no gaps between sections. 
This makes it difficult to review the ini when opened in notepad. 

Please consider adding a default separator such as blank row, blank comment (;   ), or line comment (; -----).

**Comment by gabbyhershey** [comment]
what file is tthis refering to?

**Comment by gabbyhershey** [comment]
nvm

**Comment by fluffynuts** [comment]
@gabbyhershey please update your packages & feed back if you have any issues (:
