### ISSUE TITLE
ini Remove method leaves the key behind

### ISSUE THREAD

**Issue by ixm7** [fluffynuts/PeanutButter#47]
The ini Remove method deletes the key value but leaves the key behind.

Before the call:
[mySection]
myKey="myValue"

After calling gINIFile.Item("mySection").Remove("myKey"):
[mySection]
myKey

Expected behavior is for myKey to be completely removed.

**Comment by fluffynuts** [comment]
Hi @ixm7 

This is the first I've seen of this (sorry, for some reason the default notification setup on GitHub for owners is only for security alerts ): but I've updated on this repo!) I assume this is still an issue? I'll investigate shortly.

**Comment by fluffynuts** [comment]
@ixm7 are you sure you have the correct project here? There's no `Item` method on IINIFile - the code above doesn't seem to be against PeanutButter's INIFile class?

However, if you were doing:
```csharp
gINIFile["mySection"].Remove("myKey");
```
you'd be correct that the behavior was to set the key value to null (leaving the key in place, which is valid INI syntax, but, as you say, not expected)

I've just done a release to resolve this (2.0.51) - please update when it suits you (:

Thanks for the report.

**Comment by ixm7** [comment]
Thanks!
