### ISSUE TITLE
PeanutButter.INI: CommentDelimiter not respected when saving

### ISSUE THREAD

**Issue by AxelTechnology** [fluffynuts/PeanutButter#59]
If .CommentDelimiter has been set, for example to CommentDelimiter = "'";
after calling .Persist() 
the result file contains both ; and ' are the comment header.

## Expected Behavior
[DBJUMPING]
'NOJUMPRANGE=1

## Actual Behavior
[DBJUMPING]
;'NOJUMPRANGE=1

## Steps to Reproduce the Problem
  1. set CommentDelimiter = "'"; for BestEffortLineParser derived class
  2. read the INI file
  3. save the INI file calling  .Persist() 

## Specifications
  - Version: 2.0.72
  - Platform: Windows 10 
  - Component: Visual Studio 2022

**Comment by fluffynuts** [comment]
Updated in 2.0.73. Please try it out and feed back.

**Comment by AxelTechnology** [comment]
Solved. Thank you.
