### ISSUE TITLE
PeanutButter.INI exception

### ISSUE THREAD

**Issue by AxelTechnology** [fluffynuts/PeanutButter#60]
## Expected Behavior
Work

## Actual Behavior
Exception
![immagine](https://user-images.githubusercontent.com/18584211/165941351-44447b5b-bb08-484f-971f-399527553f14.png)

## Steps to Reproduce the Problem
  1. Use a customized parser with ' as comment char
  class IniFileLineParser : BestEffortLineParser
    {
        public IniFileLineParser()
        {
            base.CommentDelimiter = "'";            
        }
    }

  2. Load a file containing one or two ' in the value, not as comment
[DATI.TXT](https://github.com/fluffynuts/PeanutButter/files/8590275/DATI.TXT)

## Specifications
  - Platform: VS 2022
  - PeanutButter Component: INI
  - PeanutButter Version: 2.0.75

**Comment by fluffynuts** [comment]
I have modified a test to use the encoding as you pass it and the test doesn't throw this error, so I need more info; specifically, the file you're dealing with, so I can track down the issue.

**Comment by AxelTechnology** [comment]
I've created a simple example to reproduce the error.
[TestPBINI.zip](https://github.com/fluffynuts/PeanutButter/files/8601709/TestPBINI.zip)

If not present, put the file DATI.TXT inside the build folder

**Comment by fluffynuts** [comment]
Please see release 2.0.76 - should resolve the issue.

**Comment by AxelTechnology** [comment]
The error is gone, but now I've seen that the 
mIniFile.Persist(Encoding.GetEncoding(1252)); //Save in ANSI

is no longer working, the file is saved always in UTF-8.
At the moment, I'm not sure if this behaviour is regarding the latest version or if is something else.

**Comment by fluffynuts** [comment]
I don't see how though? That's https://github.com/fluffynuts/PeanutButter/blob/47a2e127a874343bf7a5ed0c386a3a47d6db66ab/source/INI/PeanutButter.INI/INIFile.cs#L891-L898, which like other Persist methods, ends up going through https://github.com/fluffynuts/PeanutButter/blob/47a2e127a874343bf7a5ed0c386a3a47d6db66ab/source/INI/PeanutButter.INI/INIFile.cs#L942-L961, where we use `File.WriteAllBytes` with the provided `encoding`. What's the example?

**Comment by AxelTechnology** [comment]
Sorry, my fault, I trusted Windows.
In reality there is no problem.

I explain to you:
To check if a file is ANSI or UTF-8 I use Notepad or Notepad ++.
It seems that Windows 10, from a certain update onwards, has changed the way of interpreting files without headers, and instead of calling them ANSI it calls them UTF-8, while UTF-8 with headings calls them UTF-8 with BOM

(see image)
![compare](https://user-images.githubusercontent.com/18584211/166635191-55e6a408-2787-40db-a218-cf337027cf95.png)
.

So, never mind and thank you again.
