### ISSUE TITLE
TrayIcon NuGet package empty

### ISSUE THREAD

**Issue by spodskubka** [fluffynuts/PeanutButter#7]
Hi @fluffynuts!

I wanted to try out your TrayIcon component today but noticed that the current PeanutButter.TrayIcon NuGet package unfortunately doesn't contain any assemblies at all.
Then I looked back a bit and I think that version 1.1.44 is the last one that was actually not empty.

Am I missing something or could there be an error in the NuGet build for this package since version 1.2.0?

**Comment by fluffynuts** [comment]
Hi! This sounds like an error ): I'll sort it out post-haste. Thanks for reporting it!

**Comment by fluffynuts** [comment]
Btw, if memory serves, the code won't have changed much, if at all since 1.1.44. 1.2.x was just when I upped the target framework from 4.0 (iirc) to 4.5.2. So you can check it out at that version and hopefully I'll have the package sorted out soon so you can update. Check out the tests for usage (:

**Comment by fluffynuts** [comment]
Thanks again for reporting. This package went wonky after a code re-organisation where I put projects into solution folders and actual folders -- VS doesn't do the folder tracking game automatically, and I missed this one )':
This is now sorted (tested download) in 1.2.140.

**Comment by spodskubka** [comment]
Perfect, thanks for the quick fix!
