### ISSUE TITLE
PeanutButter.DuckTyping: Parameter count error when trying to invoke overloaded method

### ISSUE THREAD

**Issue by aracicot-fusebill** [fluffynuts/PeanutButter#76]
## Expected Behavior
Ducktyped object's method should invoke the underlying object's method matching the same signature

## Actual Behavior
Invalid Parameter count exception is thrown

## Steps to Reproduce the Problem

  1. ducktype object with overloaded method(s)
  2. try to invoke one of those methods from the ducktyped object
  3. Exception thrown

## Specifications

  - Platform: Windows 10, X64
  - PeanutButter Component:  DuckTyping
  - PeanutButter Version: 3.0.8

**Comment by aracicot-fusebill** [comment]
Looks like it's might be due to the shimsham class using a dictionary to store the method infos. If the key just the method name, I'm suspecting it might be dropping any overloads, leaving room for just one.

**Comment by fluffynuts** [comment]
fascinating! I wasn't aware anyone else was actually using this!

any ideas for a fix? PRs are appreciated (:

**Comment by fluffynuts** [comment]
I'd probably start by modifying the lookup to use a key of tuple: (string: Type[]) so that the correct overload can be selected - you're certainly using this beyond the original scope, but that's pretty cool (:

**Comment by fluffynuts** [comment]
I must admit that I rarely use this for method ducking - but I use this _a lot_ for property ducking, especially off to dictionaries and NameValueCollections, so I'm quite pleased that someone else is (a) finding it useful and (b) pushing boundaries

**Comment by fluffynuts** [comment]
@aracicot-fusebill please check out package 3.0.10 - I've implemented overloads and also improved the fuzzy ducker for the case where the interface method and the ducked type have the same parameters, just in different orders, based on type - this won't re-order according to name, ie if we have:

```
// concrete type
public class Worker
{
  public void DoWork(string str, int a)
  {
  }
}

// ducked interface
public interface IMyWorker
{
  void DoWork(int a, string foo)
  {
  }
}
```

then we can do `worker.FuzzyDuckAs<IMyWorker>()` and expect `DoWork` to work appropriately, but if we have

```
public class Stringy
{
  public void DoWork(string first, string second)
  {
  }
}

// ducked interface
public interface IMyStringy
{
  void DoWork(string second, string first);
}
```

then we can `DuckAs<IMyWorker>()` but the order of parameters will not be switched in the call

**Comment by fluffynuts** [comment]
@aracicot-fusebill have you had a chance to check out the latest package & see if it does what you're expecting?

**Comment by fluffynuts** [comment]
@aracicot-fusebill closing as I believe I've sorted this out; please re-open if need be.
